"""empty message

Revision ID: 4bb85672cfbc
Revises: d8b650b0974c
Create Date: 2021-10-05 07:16:13.510229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb85672cfbc'
down_revision = 'd8b650b0974c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_user_name_key', 'comments', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('comments_user_name_key', 'comments', ['user_name'])
    # ### end Alembic commands ###
